server:
    port: 8080
#  error:
#    whitelabel:
#      enabled: false

logging:
    level:
        com.github.fabiomqs.tasks: DEBUG
        org.springframework.web: ERROR
        org.springframework.security: ERROR
        org.hibernate: ERROR

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tasks
        username: root
    #        password: password
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect